name: Backend testing

on:
  push:
  pull-request:

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version-file: 'backend/go.mod'
          check-latest: true
          cache-dependency-path: 'backend/go.sum'

      - name: Lint with golangci-lint
        uses: golangci/golangci-lint-action@v3.6.0
        with:
          version: v1.53
          working-directory: backend

      - name: Build
        run: go build -v ./...
        working-directory: backend

      - name: Test
        run: go test -v ./...
        working-directory: backend
